server:
    port: 8090

spring:
    docker:
        compose:
            enabled: true
            file: Prueba/docker-compose.yml
    ai:
        vectorstore:
            qdrant:
                host: localhost
                port: 6333
                collection-name: examen_rag
                initialize-schema: true
                use-admin-api: true
        model:
            embedding: transformers
        embedding:
            transformer:
                onnx:
                    model-uri: classpath:models/model.onnx
                tokenizer:
                    uri: classpath:models/tokenizer.json
        openai:
            api-key: ${API_KEY}
            base-url: https://api.groq.com/openai/v1
            chat:
                options:
                    model: llama-3.3-70b-versatile

logging:
    level:
        org.springframework.ai.chat.client.advisor.SimpleLoggerAdvisor: DEBUG
