rootProject.name = "taller_3"
include("01.embeddings")
include("02.langchain4j")
include("03.spring-ai")
include("repaso_agentes")
include("11.spring-rag")
include("10.spring-prompt")
include("12.spring-mcp-client")
include("13.spring-mpc-server-stdio")
include("14.spring-mcp-server-http")