spring:
  main:
    web-application-type: none
    banner-mode: off
  ai:
    mcp:
      server:
        name: mi-mcp-server
        version: 1.0.0

# Redirige los logs para que no ensucien STDOUT
logging:
  pattern:
    console: "" # Desactiva el formato de consola por defecto en STDOUT
  # Opcionalmente puedes forzar los logs a un archivo:
  file:
    name: logs/mcp-server.log
